name: Django CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Unit Tests
      run: python manage.py test

    - name: Run Integration Tests
      run: python manage.py test

    - name: Run Flake8
      run: flake8 .

    - name: Run Black
      run: black --check .

    - name: Deploy to Cloud (replace with your deployment steps)
      run: echo "Deploying to Cloud"

